# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release example

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Modifiy the specific files using scripts
        run: |
          echo $RELEASE_VERSION
          echo $RELEASE_VERSION > .github/workflows/__version__
      - name: Commit and push changes
        run: |
          git config --global user.name "c17hawke"
          git config --global user.email "sunny.c17hawke@gmail.com"
          git add -A
          git commit -m "update current stats"
          git push